services:
  postgres:
    image: postgres:16
    container_name: control_stock_postgres
    restart: always
    environment:
      POSTGRES_DB: control_stock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: control_stock_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: control_stock
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: clave_secreta_desarrollo
      PORT: 3000
    depends_on:
      - postgres

volumes:
  postgres_data: